### ISSUE TITLE
Not able to detect python package

### ISSUE THREAD

**Issue by exploitprotocol** [j91321/rext#4]
I have installed 2.9.1 version of request python package using pip but still it is not able to detect it. Have a look at the image down below.

![](https://i.imgur.com/4zzWTzH.png)

**Comment by ivytin** [comment]
You should use the pip of **Python 3 version**. 
```bash
pip3.4 install requests
```

**Comment by exploitprotocol** [comment]
Oops! i thought this was based on Python 2 .

@j91321 Any plan for providing python2 support ?

**Comment by j91321** [comment]
The problem is not related to requests in any way. From the error message you can see there is no module named request in urllib. 

This is because urllib.request/urllib.error is successor of urllib2 module which is present in python2 (it was split in python 3.0 [see docs](https://docs.python.org/2/library/urllib2.html) )

No, I am not planning on adding python2 support. From my point of view it doesn't make any sense since everything is moving towards python3. You may however try using 3to2 to convert the code, it may work on rext core but I doubt it'll work on modules.
